version: '3.8'

services:
  # Vector Database for AI/RAG System
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-local
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped

  # Redis for caching and session management
  redis:
    image: redis:6-alpine
    container_name: redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  # PostgreSQL for data persistence (optional)
  postgres:
    image: postgres:13-alpine
    container_name: postgres-local
    environment:
      POSTGRES_DB: aasx_data
      POSTGRES_USER: aasx_user
      POSTGRES_PASSWORD: aasx_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Neo4j (if you want to use Docker version instead of Desktop)
  neo4j:
    image: neo4j:5.15-community
    container_name: neo4j-local
    environment:
      NEO4J_AUTH: neo4j/Neo4j123
      NEO4J_PLUGINS: '["apoc"]'
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/var/lib/neo4j/import
      - neo4j-plugins:/plugins
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: unless-stopped

volumes:
  qdrant-data:
  redis-data:
  postgres-data:
  neo4j-data:
  neo4j-logs:
  neo4j-import:
  neo4j-plugins: 