# AASX ETL Pipeline Configuration
# Configuration for processing AASX files in the Quality Infrastructure Digital Platform

# Pipeline Configuration
pipeline:
  enable_validation: true
  enable_logging: true
  enable_backup: true
  parallel_processing: false
  max_workers: 4

# Input Configuration
input:
  # Directory containing AASX files to process
  source_directory: "data/aasx-examples"
  # File patterns to process (default: all .aasx files)
  file_pattern: "*.aasx"
  # Specific files to process (if empty, processes all files in directory)
  specific_files: []
  # Recursive search in subdirectories
  recursive: false

# Output Configuration
output:
  # Base output directory
  base_directory: "output/etl_results"
  # Create timestamped subdirectories
  timestamped_output: true
  # Clean output directory before processing
  clean_output: false
  # Create separate outputs for each file
  separate_file_outputs: true
  # Include file name in output directory
  include_filename_in_output: true

# Transformation Configuration
transformation:
  # Enable data quality checks
  enable_quality_checks: true
  # Enable data enrichment with QI metadata
  enable_enrichment: true
  # Output formats to generate
  output_formats:
    - "json"
    - "yaml"
    - "csv"
    - "graph"
  # Include metadata in output
  include_metadata: true
  # Quality threshold (0.0 to 1.0)
  quality_threshold: 0.8
  # Normalize IDs
  normalize_ids: true
  # Add timestamps
  add_timestamps: true

# Database Configuration
database:
  # SQLite database path
  sqlite_path: "output/aasx_data.db"
  # Create database indexes
  create_indexes: true
  # Backup existing database
  backup_existing: true

# Vector Database Configuration
vector_database:
  # Enable vector database
  enabled: true
  # Vector database type (chromadb, faiss)
  type: "chromadb"
  # Vector database path
  path: "output/vector_db"
  # Embedding model
  embedding_model: "all-MiniLM-L6-v2"
  # Text chunk size for embeddings
  chunk_size: 512
  # Chunk overlap size
  overlap_size: 50
  # Include metadata in vector database
  include_metadata: true

# RAG Configuration
rag:
  # Enable RAG dataset creation
  enabled: true
  # RAG dataset output path
  output_path: "output/rag_dataset.json"
  # Include all entity types in RAG dataset
  entity_types:
    - "asset"
    - "submodel"
    - "document"
  # Minimum quality score for RAG inclusion
  min_quality_score: 0.7

# Logging Configuration
logging:
  # Log level (DEBUG, INFO, WARNING, ERROR)
  level: "INFO"
  # Log file path
  file_path: "logs/etl_pipeline.log"
  # Console output
  console_output: true
  # Include timestamps in logs
  include_timestamps: true

# Performance Configuration
performance:
  # Memory limit (MB) - 0 for no limit
  memory_limit: 0
  # Process files in batches
  batch_processing: false
  # Batch size (if batch_processing is true)
  batch_size: 10
  # Timeout for individual file processing (seconds)
  file_timeout: 300

# Error Handling
error_handling:
  # Continue processing on individual file errors
  continue_on_error: true
  # Maximum number of consecutive errors before stopping
  max_consecutive_errors: 5
  # Retry failed files
  retry_failed: false
  # Maximum retry attempts
  max_retries: 3
